<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Extensions
 * @package     Ma2_FeaturedProducts
 * @copyright   Copyright (c) 2013 MagenMarket. (http://www.magenmarket.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: standalone_list.phtml 4 2013-11-05 07:31:07Z linhnt $ */
?>

<?php
  $_helper = $this->helper('catalog/output');
  $uniqId = Mage::helper('core')->uniqHash("ma2-featuredproducts-");
  
  $list_type = $this->getMode();
?>
<div class="ma2-featuredproducts block-featured-products <?php echo $list_type; ?>-view" id="<?php echo $uniqId; ?>">
  <div class="block-inner">
    
    <?php if(!$FeaturedProductCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
      <div class="category-products" style="font-family: 'Alegreya Sans', sans-serif;">

        <?php // Grid Mode ?>
        <?php $_collectionSize = $FeaturedProductCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-grid row">
        <?php $i = 0;foreach ($FeaturedProductCollection as $_product): ?>
          <li class="col-xs-6 col-sm-3 item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
            <a href="<?php echo $_product->getProductUrl() ?>"
               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
               class="product-image"><img
                  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(220, 300); ?>"
                  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
            <div class="title-product"><a href="<?php echo $_product->getProductUrl() ?>" class="text-danger"
                                          title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
            </div>
            <div class="price-product">
              <?php echo $this->getPriceHtml($_product, true) ?>
            </div>

          </li>
        <?php endforeach ?>
        </ul>
          <script
              type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
      </div>
    <?php endif; ?>
  </div>
</div>
