<div class="category-products">
    <div class="products-grid row">
        <?php
        $_categories=$this->getCurrentChildCategories();
        if($_categories->count()):
            $categorycount = 0;
            foreach ($_categories as $_category):
                if($_category->getIsActive()):
                    $cur_category=Mage::getModel('catalog/category')->load($_category->getId());
                    $layer = Mage::getSingleton('catalog/layer');
                    $layer->setCurrentCategory($cur_category);
                    $catName = $this->getCurrentCategory()->getName();
                    /*if ($categorycount == 0){
                        $class = "first";
                    }*/
                    /*elseif ($categorycount == 3){
                        $class = "last";
                    }
                    else{
                        $class = "";
                    }*/

                    ?>
                    <div class="item col-xs-6 col-sm-4">
                        <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
                            <img src="<?php echo $_category->getImageUrl() ?>" width="283" height="240" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                            <h2><?php echo $this->htmlEscape($_category->getName()) ?></h2>
                        </a>
                    </div>
                    <?php
                endif;
                $categorycount++;
            endforeach;
        endif;
        ?>
    </div>
</div>