<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>

    <div class="qtyswitcher-add-to-cart-box table">
        <div id="qtyswitcher-btn-picto-<?php echo $_product->getId() ?>" class="table-cell">
            <button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-success" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        </div>
        <div class="qtyswitcher-qty table-cell">
            <?php if(!$_product->isGrouped()): ?>
            <?php if(!is_numeric($this->getMinimalQty($_product))) : $qty= 1; ?>
            <?php else : $qty=$this->getMinimalQty($_product);?>
            <?php endif; ?>
            <div class="table">
                <div class="input-box">
                    <div class="spinner" data-trigger="spinner" id="spinner">
                        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text clone-qty qty" data-rule="quantity">
                        <div class="spinner-controls">
                            <a href="javascript:;" data-spin="up"></a>
                            <a href="javascript:;" data-spin="down"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php else :?>
            <script language="javascript">qtyswitcher.groupedInit("<?php //echo $this->__("Quantity"); ?>")</script>
        <?php endif; ?>
    </div>

<?php endif; ?>