<!DOCTYPE html>

<html lang="en">

<head>

<!--<link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>-->

<?php echo $this->getChildHtml('head');?>

</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<div id="fb-root"></div>
<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.6";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<!-- Header part -->

	<header id="header" class="row">
		<div class="col-md-12">
			<?php echo $this->getChildHtml('header');?>
		</div>
	</header>
	
		<?php 
if( Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && 
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) { /* if is home page */?>	
	<?php echo $this->getLayout()->createBlock('customblocks/mainblock')->setTemplate('customblocks/mainblock.phtml')->toHtml(); ?>
	<?php } ?>

	

	<div class="container" style="padding-top:50px">
<br/>	
	<?php echo $this->getChildHtml('content');?>

	</div>
	
	
	<?php 
if( Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && 
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) { /* if is home page */?>	
	<?php echo $this->getLayout()->createBlock('customblocks/customblock')->setTemplate('customblocks/brandblocks.phtml')->toHtml(); ?>
	<?php } ?>	

<div class="container">
	<?php 
if( Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && 
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) { /* if is home page */?>	
	<?php echo $this->getLayout()->createBlock('customblocks/customblock')->setTemplate('customblocks/bottomblock.phtml')->toHtml(); ?>
	<?php } ?>
	</div>
	

	<!--Footer part-->
	<div class="footer">
		<div class="col-md-12">
	  		<?php echo $this->getChildHtml('footer');?>
	  	</div>
	</div>
</body>
</html>