<!DOCTYPE html>
<html lang="en">
<head>
<!--<link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>-->
<?php echo $this->getChildHtml('head');?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>


<!-- Header part -->

<header id="header" class="row">
	<div class="col-md-12">
		<?php echo $this->getChildHtml('header');?>
	</div>
</header>
	
	<div class="slider">
<div class="img-test" style="height:650px"></div>	
	</div>
	
	<div class="container">
	<?php echo $this->getChildHtml('content');?>
	</div>
	
	<!--Footer part-->
	<div class="footer">
		<div class="col-md-12">
	  		<?php echo $this->getChildHtml('footer');?>
	  	</div>
	</div>




</body>

</html>